version: '3.7'

services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - './static:/static'
    ports:
      - '2485:8080'
  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test"]
      interval: 5s
      retries: 5
    ports:
      - '5687:5432'
    env_file:
      - .env
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: 'uvicorn general.main:app --port 8000 --host 0.0.0.0 --workers 1'
    volumes:
      - ./app:/code
    env_file:
      - .env
    depends_on:
      init:
        condition: service_completed_successfully
  init:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: alembic upgrade head
    volumes:
      - ./app:/code
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
